databases:
  - name: rock-paper-scissors-db
    plan: free
    databaseName: rps_leaderboard
    user: rps_user

services:
  - type: web
    name: rock-paper-scissors
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rock-paper-scissors-db
          property: connectionString
